name: agro_millets
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
#  easy_localization:
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  firebase_messaging: ^14.4.0
  flutter_local_notifications: 13.0.0
  photo_view: 0.14.0
  firebase_auth: ^4.4.0
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  flutter_map: ^3.0.0
  dio: ^5.1.2
  flutter_spinkit: ^5.2.0
  get: ^4.6.5
  get_storage: ^2.1.1
  geolocator:
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.2
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.5.0
  firebase_app_check: ^0.1.4+2
  open_street_map_search_and_pick: ^0.0.17
  http: ^0.13.6
  image_picker: ^0.8.7
  latlong2:
  material_design_icons_flutter: ^6.0.7096
  package_info_plus: ^3.1.0
  shared_preferences: ^2.1.0
  timeago: ^3.3.0
  uuid: ^3.0.7
  location:
  intl: ^0.18.1
  supercharged: ^2.1.1
  smooth_page_indicator: ^1.1.0
  simple_animations: ^5.0.0+3
  provider: ^6.0.5
  url_launcher: ^6.1.11
  cached_network_image:
  pinput: ^2.2.31
  mailer: ^6.0.1
  flutter_svg: ^2.0.2
  khalti: ^1.1.0
  geocoding: ^2.0.0
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  

  assets:
    - assets/translations/.
    - assets/.